# Generated by Django 5.0 on 2026-05-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Alimentação, Salário, Investimentos', max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita (Entrada)'), ('DESPESA', 'Despesa (Saída)')], max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: NuConta, Carteira, Bradesco', max_length=100, verbose_name='Nome da Conta')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual (R$)')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='SimulacaoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Aposentadoria, Compra de Carro', max_length=100, verbose_name='Título da Simulação')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Inicial (R$)')),
                ('aporte_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte Mensal (R$)')),
                ('taxa_juros_anual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros Anual (%)')),
                ('periodo_meses', models.IntegerField(verbose_name='Período (Meses)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Simulação de Investimento',
                'verbose_name_plural': 'Simulações de Investimento',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data', models.DateField(verbose_name='Data da Transação')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria', verbose_name='Categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.contabancaria', verbose_name='Conta Bancária')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
