# Generated by Django 5.0 on 2026-05-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sua receita média mensal fixa', max_digits=12, verbose_name='Renda Mensal (R$)')),
                ('meta_patrimonio', models.DecimalField(decimal_places=2, default=0.0, help_text='Quanto você deseja acumular no total', max_digits=12, verbose_name='Meta de Patrimônio (R$)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
